/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SpaLogo {
        /**
          * The logo src
         */
        "src": string;
    }
}
declare global {
    interface HTMLSpaLogoElement extends Components.SpaLogo, HTMLStencilElement {
    }
    var HTMLSpaLogoElement: {
        prototype: HTMLSpaLogoElement;
        new (): HTMLSpaLogoElement;
    };
    interface HTMLElementTagNameMap {
        "spa-logo": HTMLSpaLogoElement;
    }
}
declare namespace LocalJSX {
    interface SpaLogo {
        /**
          * The logo src
         */
        "src"?: string;
    }
    interface IntrinsicElements {
        "spa-logo": SpaLogo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "spa-logo": LocalJSX.SpaLogo & JSXBase.HTMLAttributes<HTMLSpaLogoElement>;
        }
    }
}
